#!/bin/bash

NVIM_REPOSITORY="git@github.com:JannikStr/NeoVim-Config.git"

export XDG_CONFIG_HOME="$HOME/.config"

mkdir -p "$XDG_CONFIG_HOME"/nixpkgs

git clone -b lua "$NVIM_REPOSITORY" $XDG_CONFIG_HOME/nvim
(cd "$XDG_CONFIG_HOME/nvim"; git apply $HOME/dotfiles/patches/nvim.patch)

ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim

ln -sf "$PWD/config.nix" "$XDG_CONFIG_HOME/nixpkgs/config.nix"

ln -sf "$PWD/.tmux.conf" "$HOME/.tmux.conf"

nix-env -iA nixpkgs.myPackages

cat "$PWD/.zshrc-appendings" >> "$HOME/.zshrc"
